services:
  auth-service:
    build: ./services/auth-service
    ports:
      - "3001:3001"
    env_file:
      - ./services/auth-service/.env
    depends_on:
      kafka:
        condition: service_healthy

  parking-service:
    build: ./services/parking-service
    ports:
      - "3002:3002"
    env_file:
      - ./services/parking-service/.env
    depends_on:
      kafka:
        condition: service_healthy
      auth-service:
        condition: service_started

  reservation-service:
    build: ./services/reservation-service
    ports:
      - "3003:3003"
    env_file:
      - ./services/reservation-service/.env
    depends_on:
      kafka:
        condition: service_healthy
      parking-service:
        condition: service_started

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.7.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    healthcheck:
      # Kafka është "healthy" kur porti 29092 është i hapur brenda container-it
      test: ["CMD-SHELL", "bash -lc 'nc -z localhost 29092'"]
      interval: 5s
      timeout: 3s
      retries: 30

  init-kafka:
    image: confluentinc/cp-kafka:7.7.0
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ["/bin/bash", "-lc"]
    command: |
      echo "Creating topics..." &&
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic parking-events --partitions 1 --replication-factor 1 &&
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic reservation-events --partitions 1 --replication-factor 1 &&
      echo "Topics ready."
